test:
  chrome:
    id: cobkhjnnnbmaigjhgpmmlkmaidbhpinb

testserver:
  chrome:
    id: bmekjogijonolmphikpeppogdmcclkfc

staging:
  chrome:
    id: cobkhjnnnbmaigjhgpmmlkmaidbhpinb

production:
  chrome:
    id: cobkhjnnnbmaigjhgpmmlkmaidbhpinb
