test:
  chrome:
    ids:
      - cobkhjnnnbmaigjhgpmmlkmaidbhpinb

development:
  chrome:
    ids:
      - kkihgbnaciigoekfgfgjpjggojlobigh

testserver:
  chrome:
    ids:
      - bmekjogijonolmphikpeppogdmcclkfc

staging:
  chrome:
    ids:
      - fkhpmbcgikfdnnobmembneidakkifjgp

production:
  chrome:
    ids:
      - cobkhjnnnbmaigjhgpmmlkmaidbhpinb
      - pbmlhihdhmjopieoohffemicnggdmbci