test:
  chrome:
    id: cobkhjnnnbmaigjhgpmmlkmaidbhpinb

development:
  chrome:
    id: kkihgbnaciigoekfgfgjpjggojlobigh

testserver:
  chrome:
    id: bmekjogijonolmphikpeppogdmcclkfc

staging:
  chrome:
    id: cobkhjnnnbmaigjhgpmmlkmaidbhpinb

production:
  chrome:
    id: cobkhjnnnbmaigjhgpmmlkmaidbhpinb
