test:
  chrome:
    id: cobkhjnnnbmaigjhgpmmlkmaidbhpinb

development:
  chrome:
    id: kkihgbnaciigoekfgfgjpjggojlobigh

testserver:
  chrome:
    id: bmekjogijonolmphikpeppogdmcclkfc

vagrant:
  chrome:
    id: bmekjogijonolmphikpeppogdmcclkfc

staging:
  chrome:
    id: fkhpmbcgikfdnnobmembneidakkifjgp

production:
  chrome:
    id: cobkhjnnnbmaigjhgpmmlkmaidbhpinb
