development:
  chrome:
    id: not_available

test:
  chrome:
    id: cobkhjnnnbmaigjhgpmmlkmaidbhpinb

testserver:
  chrome:
    id: cobkhjnnnbmaigjhgpmmlkmaidbhpinb

staging:
  chrome:
    id: cobkhjnnnbmaigjhgpmmlkmaidbhpinb

production:
  chrome:
    id: cobkhjnnnbmaigjhgpmmlkmaidbhpinb
