default: &default
  socket: /tmp/.s.PGSQL.5432
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: factlink_development

test:
  <<: *default
  database: factlink_test

staging:
  adapter: postgres
  database: factlink_staging
  host: factlink-postgresql-staging.inverselink.com
  username: postgres
  password: "EfS-W3P3v:tOivmrHsPl9.8i2,xwO3asVcju:DGB:x,RIF.1Ksm4R6XrvGtZhppo63txK79Azonqm_ZLIlIMpiyJjEXxx9Hpu,sp"
  pool: 5
  timeout: 5000

production:
  adapter: postgres
  database: factlink_production
  host: factlink-postgresql-production.inverselink.com
  username: postgres
  password: "NrrOG7R8CJ4PQ9kLx_sV8NM,Y87wbjHdVEUZ5egn,7tiJLPsmte0zZHVB.1UUEgm4KPSPLF:AT.8uqt9b0erlQPuT.zyIo-1yA,3"
  pool: 5
  timeout: 5000
