development:
  elasticsearch:
    hostname: localhost
    port: 9200

test:
  elasticsearch:
    hostname: localhost
    port: 9200

testserver:
  elasticsearch:
    hostname: 172.18.64.2
    port: 9200

vagrant:
  elasticsearch:
    hostname: 10.253.0.1
    port: 9200

staging:
  elasticsearch:
    hostname: 172.18.100.37
    port: 9200

production:
  elasticsearch:
    hostname: 89.188.27.179
    port: 9200
