development:
  elasticsearch:
    hostname: localhost
    port: 9200
    cluster: factlink_development

test:
  elasticsearch:
    hostname: localhost
    port: 9200
    cluster: factlink_test

testserver:
  elasticsearch:
    hostname: 89.188.27.177
    port: 9200
    cluster: factlink_testserver

staging:
  elasticsearch:
    hostname: 89.188.27.178
    port: 9200
    cluster: factlink_staging

production:
  elasticsearch:
    hostname: localhost
    port: 9200
    cluster: factlink_production
