development:
  elasticsearch:
    hostname: localhost
    port: 9200

test:
  elasticsearch:
    hostname: localhost
    port: 9200

testserver:
  elasticsearch:
    hostname: 172.18.64.2
    port: 9200

vagrant:
  elasticsearch:
    hostname: 10.253.0.1
    port: 9200

staging:
  elasticsearch:
    hostname: 172.18.64.11
    port: 9200

production:
  elasticsearch:
    hostname: 172.18.64.27
    port: 9200
