development:
  host: localhost
  database: factlink_ui_development

test:
  host: localhost
  database: factlink_ui_test

testserver:
  host: localhost
  port: 27017
  database: factlink_ui_production

staging:
  database: factlink_staging
  hosts:
    - - mongo1-staging.factlink.com
      - 27018
    - - mongo2-staging.factlink.com
      - 27018
    - - mongo3-staging.factlink.com
      - 27018

production:
  host: localhost
  port: 27017
  database: factlink_ui_production
