development:
  sessions:
    default:
      database: factlink_ui_development
      hosts:
       - localhost:27017
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: factlink_ui_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
  options:
    raise_not_found_error: false

testserver:
  sessions:
    default:
      database: factlink_testserver
      hosts:
       - 89.188.27.138:27017
       - 89.188.27.139:27017
      options:
        consistency: :strong
  options:
    raise_not_found_error: false

staging:
  sessions:
    default:
      database: factlink_staging
      hosts:
       - 89.188.27.140:27017
       - 89.188.27.186:27017
      options:
        consistency: :strong
  options:
    raise_not_found_error: false

production:
  sessions:
    default:
      database: factlink_ui_production
      hosts:
       - mongo4-production.factlink.com:27017
       - 89.188.27.146:27017
       - 89.188.27.148:27017
      options:
        consistency: :strong
  options:
    raise_not_found_error: false
