development:
  sessions:
    default:
      database: factlink_ui_development
      hosts:
       - localhost:27017
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: factlink_ui_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
  options:
    raise_not_found_error: false

testserver:
  sessions:
    default:
      database: factlink_testserver
      hosts:
       - 172.18.64.8:27017
       - 172.18.64.9:27017
       - 172.18.64.10:27017
      options:
        consistency: :strong
  options:
    raise_not_found_error: false

vagrant:
  sessions:
    default:
      database: factlink_ui_development
      hosts:
       - 10.253.0.1:27017
  options:
    raise_not_found_error: false

staging:
  sessions:
    default:
      database: factlink_staging
      hosts:
       - 172.18.64.16:27017
       - 172.18.64.19:27017
      options:
        consistency: :strong
  options:
    raise_not_found_error: false

production:
  sessions:
    default:
      database: factlink_ui_production
      hosts:
       - 89.188.27.146:27017
       - 89.188.27.148:27017
       - 172.18.100.24:27017
       - 172.18.100.29:27017
       - 172.18.100.30:27017
       - 172.18.100.31:27017
       - 172.18.100.61:27017
      options:
        consistency: :strong
  options:
    raise_not_found_error: false
