development:
  sessions:
    default:
      database: factlink_ui_development
      hosts:
       - localhost:27017
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: factlink_ui_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
  options:
    raise_not_found_error: false

testserver:
  sessions:
    default:
      database: factlink_testserver
      hosts:
       - mongo1-testserver.factlink.com:27019
       - mongo2-testserver.factlink.com:27019
       - mongo3-testserver.factlink.com:27019
      options:
        consistency: :strong
  options:
    raise_not_found_error: false

staging:
  sessions:
    default:
      database: factlink_staging
      hosts:
       - mongo1-staging.factlink.com:27018
       - mongo2-staging.factlink.com:27018
      options:
        consistency: :strong
  options:
    raise_not_found_error: false

production:
  sessions:
    default:
      database: factlink_ui_production
      hosts:
       - mongo1-production.factlink.com:27017
       - mongo3-production.factlink.com:27017
       - mongo4-production.factlink.com:27017
      options:
        consistency: :strong
  options:
    raise_not_found_error: false
