development:
  host: localhost
  database: factlink_ui_development

test:
  host: localhost
  database: factlink_ui_test

testserver:
  database: factlink_ui_production
  hosts:
    - - mongo1-testserver.factlink.com
      - 27019
    - - mongo2-testserver.factlink.com
      - 27019
    - - mongo3-testserver.factlink.com
      - 27019

staging:
  host: localhost
  port: 27018
  database: factlink_staging

production:
  host: localhost
  port: 27017
  database: factlink_ui_production
