development:
  host: localhost
  database: factlink_ui_development

test:
  host: localhost
  database: factlink_ui_test

testserver:
  host: localhost
  port: 27017
  database: factlink_ui_production

staging:
  host: localhost
  port: 27018
  database: factlink_staging
      
production:
  host: localhost
  port: 27017
  database: factlink_ui_production  
