development:
    host: localhost
    database: factlink_ui_development

test:
    host: localhost
    database: factlink_ui_test
      
production:
    host: localhost
    port: 27017
    database: factlink_ui_production  
