development:
  host: localhost
  database: factlink_ui_development

test:
  host: localhost
  database: factlink_ui_test

testserver:
  database: factlink_testserver
  hosts:
    - - mongo1-testserver.factlink.com
      - 27019
    - - mongo2-testserver.factlink.com
      - 27019
    - - mongo3-testserver.factlink.com
      - 27019

staging:
  database: factlink_staging
  hosts:
    - - mongo1-staging.factlink.com
      - 27018
    - - mongo2-staging.factlink.com
      - 27018
    - - mongo3-staging.factlink.com
      - 27018

production:
  database: factlink_ui_production
  hosts:
    - - mongo1-production.factlink.com
      - 27017
    - - mongo2-production.factlink.com
      - 27017
    - - mongo3-production.factlink.com
      - 27017
    - - mongo4-production.factlink.com
      - 27017

