development:
  omniauth:
    facebook:
      id: "283748838400237"
      secret: "9d3776e82a8e050f615838bb9b32d13f"
    twitter:
      id: "e88X667rNJwV3qUU1FP38Q"
      secret: "PzyaLeimuKB9vFnaQQePk76QSXwp11nUZKxpk83E"

test:
  omniauth:
    facebook:
      id: "283748838400237"
      secret: "9d3776e82a8e050f615838bb9b32d13f"
    twitter:
      id: "e88X667rNJwV3qUU1FP38Q"
      secret: "PzyaLeimuKB9vFnaQQePk76QSXwp11nUZKxpk83E"

testserver:
  omniauth:
    facebook:
      id: "394296183970720"
      secret: "7b82d480717098805e22524f87e3893f"
    twitter:
      id: "2mqTPE21rj9R4fcPI6FPQ"
      secret: "y4i9T3Q1CSvU6IsTfUUKNYjEP5414JEqSnY03e2YtM"

vagrant:
  omniauth:
    facebook:
      id: "394296183970720"
      secret: "7b82d480717098805e22524f87e3893f"
    twitter:
      id: "2mqTPE21rj9R4fcPI6FPQ"
      secret: "y4i9T3Q1CSvU6IsTfUUKNYjEP5414JEqSnY03e2YtM"

staging:
  omniauth:
    facebook:
      id: "435991923110591"
      secret: "e27771470b8c341cb144367f7938a900"
    twitter:
      id: "tn5TO9XnyZhyCvGlZqkQ"
      secret: "WJj6vPjrxn13gI99w0ZZuWjqccU8EX6voY62WztaRc"

production:
  omniauth:
    facebook:
      id: "385144638222636"
      secret: "caeb481a2676854f6724b52838407faa"
    twitter:
      id: "gbis6EUPWZvEJFApQ3KA"
      secret: "YVdJAHDFKqwZJPE1rqbojYXxj8wx7430PjH1cEaHI"
