development:
    proxy:
        hostname: localhost
        port: 8080

test:
    proxy:
        hostname: localhost
        port: 8080

testserver:
    proxy:
        hostname: proxy.testserver.factlink.com
        port: 8080

production:
    proxy:
        hostname: proxy.factlink.com
        port: 8080