development:
  mongoid:
    host: localhost
    database: factlink_ui_development
  redis:
    hostname: localhost
    port: 6379
    database: 0
  proxy:
    hostname: localhost
    port: 8080

test:
  mongoid:
    host: localhost
    database: factlink_ui_test
  redis:
    hostname: localhost
    port: 6379
    database: 1
  proxy:
    hostname: localhost
    port: 8080
      
production:
  mongoid:
    host: localhost
    port: 27017
    database: factlink_ui_production  
  redis:
    hostname: localhost
    port: 6379
    database: 0
  proxy:
    hostname: proxy.factlink.com
    port: 8080