development:
  redis:
    hostname: localhost
    port: 6379
    database: 0

test:
  redis:
    hostname: localhost
    port: 6379
    database: 1
      
production:
  redis:
    hostname: localhost
    port: 6379
    database: 0
