development:
  redis:
    hostname: localhost
    port: 6381

test:
  redis:
    hostname: localhost
    port: 6379

testserver:
  redis:
    hostname: localhost
    port: 6379

staging:
  redis:
    hostname: localhost
    port: 6379

production:
  redis:
    hostname: localhost
    port: 6379
