development:
  redis:
    host: localhost
    port: 6381

test:
  redis:
    host: localhost
    port: 6379

testserver:
  redis:
    host: 89.188.27.172
    port: 6379

chef:
  redis:
    host: 10.253.0.1
    port: 6381

staging:
  redis:
    host: 89.188.27.176
    port: 6379

production:
  redis:
    host: 89.188.27.175
    port: 6379
