development:
  redis:
    host: localhost
    port: 6381

test:
  redis:
    host: localhost
    port: 6379

testserver:
  redis:
    host: 172.18.64.5
    port: 6379

vagrant:
  redis:
    host: 10.253.0.1
    port: 6381

staging:
  redis:
    host: 172.18.64.14
    port: 6379

production:
  redis:
    host: 172.18.100.45
    port: 6379
