development:
  redis:
    hostname: localhost
    port: 6381
    database: 0

test:
  redis:
    hostname: localhost
    port: 6379
    database: 1

testserver:
  redis:
    hostname: localhost
    port: 6379
    database: 0

staging:
  redis:
    hostname: localhost
    port: 6379
    database: 0

production:
  redis:
    hostname: localhost
    port: 6379
    database: 0
