development:
  redis:
    hostname: localhost
    port: 6381

test:
  redis:
    hostname: localhost
    port: 6379

testserver:
  redis:
    hostname: localhost
    port: 6379

staging:
  redis:
    host: 89.188.27.176
    port: 6379

production:
  redis:
    host: 89.188.27.175
    port: 6379
