language: ruby
rvm:
- 2.1.2
script:
- psql -c 'create database factlink_test;' -U postgres
- bundle exec rake db:setup
- bundle exec rspec spec --profile
- bundle exec rake konacha:load_poltergeist konacha:run
- bundle exec rspec spec/acceptance --profile
- "bundle exec rspec spec/screenshots --profile || (./bin/upload_screenshots_to_imgur.sh && false)"
- bundle exec brakeman --except SessionSettings -q -z
# - bundle exec scss-lint app/assets/stylesheets/ --config .scss-lint.yml  # Enable when sass-rails is updated
- bin/check_assets_updated.sh
- bundle exec rails_best_practices --silent
addons:
  code_climate:
    repo_token: 5bc532dd697587893f279a75aace11528bd17b63066856a48d22ddf40c7e8303
  postgresql: 9.3
env:
  global:
    secure: CbmWdGADWYK8KQzkWq6mspZWJfIOyTKWiOkGgFFpXvnxaelxd+eQXEdj2DVEQwjzzS/IVu5ymzd30OB+mYPObH3svzNj6p9l4Z8aRgTMZv2Kr68FyLj4bgj91kNqeWSfoozERtbUALtVGvgtpZ/FCyRrs1M0RaHosRMLI51QZLA=
