language: ruby
rvm:
  - "2.1.2"
script: "bundle exec rspec spec --profile && bundle exec rake konacha:load_poltergeist konacha:run && bundle exec rspec spec/acceptance spec/screenshots --profile && bundle exec brakeman --except SessionSettings -q -z && bin/check_assets_updated.sh && bundle exec rails_best_practices --silent"
addons:
  code_climate:
    repo_token: 5bc532dd697587893f279a75aace11528bd17b63066856a48d22ddf40c7e8303
