require 'spec_helper'
require 'pavlov'
require 'pavlov/alpha_compatibility'
require_relative '../app/interactors/util/can_can.rb'
require_relative '../app/interactors/util/validations.rb'
require_relative '../app/interactors/util/pavlov_context_serialization.rb'
require_relative 'support/unit/pavlov_support.rb'
