source 'http://rubygems.org'

ruby '2.0.0'

# Defaults
gem 'rails', '3.2.13' # this is too important to update automaticly
gem 'activerecord', '3.2.13' # this is too important to update automaticly
gem 'bcrypt-ruby', '~> 3.0.1'
gem 'sqlite3', '~> 1.3.7' # TODO: seems to break rails when removed
gem 'rake', '~> 10.0.4', require: false

gem 'addressable', '~> 2.3.4'

gem 'mail', '2.5.3' # newer versions seem to timeout sending mail. Seems like large changes on patchlevel?

# Mongo
gem 'mongoid', '~> 3.0.21'
gem 'moped', github: 'Factlink/moped', branch: '1.4.0-stable'

gem 'pavlov', github: 'Factlink/pavlov', ref: '0b4bd6af62c4210b4c9b7187eb82b3780c755213'
gem 'korsakov', github: 'jjoos/korsakov', ref: '72db865b99a3e8dee2840a191fe67ecd8f32ccef'

# Redis
gem 'redis', '~> 2.2.1'
gem 'ohm', github: 'Factlink/ohm' # we need the tribalvibes fork (0.1.4), for polymorphism
gem 'ohm-contrib', github: 'Factlink/ohm-contrib'
gem 'redis-aid', '~> 0.1.0'
gem 'redis-objects', '~> 0.5.3'
gem 'multi_json', '~> 1.7.3'

# We should upgrade this to at least the latest 1.* version,
# but 1.23.1 has a breaking change, and 1.24+ requires a redis-namespace
# which requires redis > 3.0
gem 'resque', '= 1.23.0', require: 'resque/server'
gem 'resque_mailer', '~> 2.2.3'

gem 'stringex', '~> 1.5.1'

gem 'mixpanel', github: 'Factlink/mixpanel'

gem "sentry-raven", '= 0.4.6' # Upgrading to 0.4.8 breaks error reporting from the web-app
gem "resque-sentry", '~> 0.1.0'

# Everyone loves JSON
gem 'json', '~> 1.8.0'
gem 'jbuilder', '~> 1.4.1'

# Needed for migrations to be compatible when no sql backend is available
gem 'mongoid_rails_migrations', '1.0.1' # TODO look if this needs to be pinned

# User authentication and authorization
gem 'devise', '~> 2.2.3'
gem 'devise_invitable', '= 1.1.6' # locked down version, because we had trouble upgrading @ hackerone when upgrading from 1.1.6 to 1.1.8
gem 'cancan', '~> 1.6.10'

# social connections
gem 'omniauth-facebook', '~> 1.4.1'
gem 'omniauth-twitter', '= 0.0.14' # locked down, because semver does not appear to be used
gem 'twitter', '~> 4.7.0'

# social sharing
gem 'koala', '~> 1.7.0rc1'

gem 'httparty', '~> 0.10.2'

# Andand is a library to handle nil more easily
gem 'andand', '~> 1.3.3'

#browser detection
gem 'browser', '~> 0.2.0'


gem 'capistrano', '~> 2.15.4', require: false
gem 'capistrano-ext', '~> 1.2.1',  require: false

gem 'roadie', '~> 2.3.4'

# Set X-Frame-Headers
gem 'rack-xframe-options', github: 'Factlink/rack-xframe-options'
gem 'rack-rewrite', '~> 1.3.3'

group :production do
  gem 'newrelic_moped', '~> 0.0.6'
  gem 'newrelic-redis', '~> 1.4.0'
  gem 'newrelic_rpm', '~> 3.6.2'
end

group :assets do
  gem 'less-rails', '~> 2.2.6' # cannot be updated to 2.3* without updating less-rails-bootstrap
  gem 'uglifier', '~> 1.3.0'
  gem 'hogan_assets', '~> 1.0.3'

  gem 'therubyracer', '~> 0.11.4'

  gem 'jquery-rails', '= 2.1.2' # we want a specific version of the js library
  gem 'less-rails-bootstrap', '= 2.1.1' # we want a specific version of the js library
  gem 'modernizr-rails', "= 2.0.6" # we want a specific version of the js library

  gem "rails-backbone", '= 0.7.2' # we want a specific version of the js library

  gem "marionette-rails", '= 1.0.0.rc.2' # we want a specific version of the js library
end

group :development do
  # we allow all development gems to update always
  # since we will notice when this fails

  # mesa want speed:
  gem 'rails-dev-tweaks', '~> 0'
  gem 'pry', '~> 0', require: false

  #for static files serving
  gem 'rack', '~> 1'
  gem 'thin', '~> 1'

  gem 'mailcatcher', '~> 0', require: false

  gem 'lograge', '~> 0'
  gem 'sextant', '~> 0'

  # SHUT THE FUCK UP
  gem 'quiet_assets', '~> 1'
  # Profiling
  gem 'ruby-prof', '~> 0'
end

group :test do
  # we allow tests to upgrade everything but major
  gem 'rspec-rails', '~> 2.13'
  gem 'factory_girl_rails', '~> 4.2'
  gem 'database_cleaner', '~> 0.9'

  gem 'capybara', '~> 1.1', require: false
  gem 'capybara-screenshot', '= 0.3.6' # updating breaks something with files, https://github.com/mattheworiordan/capybara-screenshot/commit/d21b51b66fc6766e32176b7b22f5d06530efea4b?w=1
  gem 'capybara-email', '~> 1.0'
  gem 'poltergeist', '~> 1.0', require: false

  gem 'oily_png', '~> 1.1'

  gem 'rb-fsevent', '~> 0.9.1'
  gem 'guard', '~> 1.8', require: false
  gem 'guard-rspec', '~> 3.0', require: false
  gem 'terminal-notifier-guard', '~> 1.5', require: false

  gem 'approvals', '~> 0' # not locked, since test will break if something goes wrong here
  gem 'timecop', '~> 0.6'
end

group :test, :development do # TODO why is there a :development here?
  # we allow tests to upgrade everything but major
  gem 'konacha', '~> 3.0'
  gem 'sinon-chai-rails', '~> 1.0'
  gem 'sinon-rails', '~> 1.4'
  gem 'yarjuf', '~> 1.0', require: false #formatter for rspec
  gem 'rspec_junit_formatter', require:false  #formatter for konacha since yarjuf doesn't work.
  #rspec_junit_formatter has no version.
end

group :development do
  gem 'brakeman', '~> 1', require: false # always update, we want the latest version always
  gem 'cane', '~> 2', require: false
  gem 'rails_best_practices', '~> 1', require: false
  gem 'rubocop', require: false
  gem 'hub', '~> 1', require: false
end
