source 'http://rubygems.org'

# for rvm:
#ruby=1.9.3-p374
# for bundler
ruby '1.9.3'

# Defaults
gem 'rails', '3.2.13' # this is too important to update automaticly
gem 'activerecord', '3.2.13' # this is too important to update automaticly
gem 'bcrypt-ruby', '~> 3.0.1'
gem 'sqlite3', '~> 1.3.7' # TODO: seems to break rails when removed
gem 'rake', '~> 0.9.2', require: false
gem 'memoist', '~> 0.2.0' # TODO: remove

gem 'addressable', '~> 2.3.4'

# Mongo
gem 'mongoid', '~> 3.0.21'
gem 'moped', git: 'git@github.com:Factlink/moped.git', branch: '1.4.0-stable'

gem 'pavlov', git: 'git@github.com:Factlink/pavlov.git', ref: 'f95f3775961046151114ce13cb9dcb1091f56777'

# Redis
gem 'redis', '~> 2.2.1'
gem 'ohm', git: 'git@github.com:Factlink/ohm.git' # we need the tribalvibes fork (0.1.4), for polymorphism
gem 'ohm-contrib', git: 'git@github.com:Factlink/ohm-contrib.git'
gem 'redis-aid', '~> 0.1.0'
gem 'redis-objects', '~> 0.5.3'
gem 'multi_json', '~> 1.7.3'

gem 'resque', '~> 1.23.0', require: 'resque/server'
gem 'resque_mailer', '~> 2.2.3'

gem 'stringex', '~> 1.5.1'

gem 'mixpanel', git: 'git@github.com:Factlink/mixpanel.git'

gem "sentry-raven", '~> 0.4.4'
gem "resque-sentry", '~> 0.1.0'

# Everyone loves JSON
gem 'json', '~> 1.7.7'
gem 'jbuilder', '~> 1.0.2'

# Needed for migrations to be compatible when no sql backend is available
gem 'mongoid_rails_migrations', '1.0.1' # TODO look if this needs to be pinned

# User authentication and authorization
gem 'devise', '~> 2.2.3'
gem 'devise_invitable', '= 1.1.6' # locked down version, because we had trouble upgrading @ hackerone when upgrading from 1.1.6 to 1.1.8
gem 'cancan', '~> 1.6.10'

# social connections
gem 'omniauth-facebook', '~> 1.4.1'
gem 'omniauth-twitter', '= 0.0.14' # locked down, because semver does not appear to be used

gem 'httparty', '~> 0.10.2'

# Andand is a library to handle nil more easily
gem 'andand', '~> 1.3.3'

#browser detection
gem 'browser', '~> 0.1.6'


gem 'capistrano', '~> 2.14.2', require: false
gem 'capistrano-ext', '~> 1.2.1',  require: false
gem 'rvm-capistrano', '~> 1.2.7', require: false

gem 'roadie', '~> 2.3.4'

# imagemagick
gem 'rmagick', '~> 2.13.2', require: false

# Set X-Frame-Headers
gem 'rack-xframe-options', git: 'git@github.com:Factlink/rack-xframe-options.git'
gem 'rack-rewrite', '~> 1.3.3'

group :production do
  gem 'newrelic_moped', '~> 0.0.6'
  gem 'newrelic-redis', '~> 1.4.0'
  gem 'newrelic_rpm', '~> 3.6.2'
end

group :assets do
  gem 'less-rails', '~> 2.2.6'
  gem 'uglifier', '~> 1.3.0'
  gem 'hogan_assets', '~> 1.0.3'

  gem 'therubyracer', '~> 0.11.4'

  gem 'jquery-rails', '= 2.1.2' # we want a specific version of the js library
  gem 'less-rails-bootstrap', '= 2.1.1' # we want a specific version of the js library
  gem 'modernizr-rails', "= 2.0.6" # we want a specific version of the js library

  gem "rails-backbone", '= 0.7.2' # we want a specific version of the js library

  gem "marionette-rails", '= 1.0.0.rc.2', git: 'git@github.com:janpaul123/marionette-rails.git'  # we want a specific version of the js library
end

group :development do
  # we allow all development gems to update always
  # since we will notice when this fails

  # mesa want speed:
  gem 'rails-dev-tweaks', '~> 0'
  gem 'pry', '~> 0', require: false

  #for static files serving
  gem 'rack', '~> 1'
  gem 'thin', '~> 1'

  gem 'letter_opener', '~> 1'

  gem 'lograge', '~> 0'
  gem 'sextant', '~> 0'

  gem 'rb-readline', '~> 0' # needed for Guard

  # SHUT THE FUCK UP
  gem 'quiet_assets', '~> 1'
  # Profiling
  gem 'ruby-prof', '~> 0'
end

group :test do
  # we allow tests to upgrade everything but major
  gem 'rspec-rails', '~> 2.13'
  gem 'factory_girl_rails', '~> 3.6'
  gem 'database_cleaner', '~> 0.9'
  gem 'mock_redis', '~> 0.7' # TODO remove

  gem 'capybara', '~> 1.1', require: false
  gem 'capybara-screenshot', '~> 0.3'
  gem 'capybara-email', '~> 1.0'
  gem 'poltergeist', '~> 1.0', require: false

  gem 'oily_png', '~> 1.1'

  gem 'headless', '~> 1.0'

  gem 'rb-fsevent', '~> 0.9.1'
  gem 'guard', '~> 1.8'
  gem 'guard-rspec', '~> 3.0'

  gem 'approvals', '~> 0' # not locked, since test will break if something goes wrong here
  gem 'timecop', '~> 0.6'
end

group :test, :development do # TODO why is there a :development here?
  # we allow tests to upgrade everything but major
  gem 'konacha', '~> 2.7'
  gem 'sinon-chai-rails', '~> 1.0'
  gem 'sinon-rails', '~> 1.4'
end

gem 'brakeman', '~> 1', require: false # always update, we want the latest version always
