source 'http://rubygems.org'

# Defaults
gem 'rails', '3.1.3'
gem 'activerecord', '3.1.3'
gem "bcrypt-ruby", "~> 3.0.1"

gem 'sqlite3-ruby', :require => 'sqlite3'

gem 'rake', '~> 0.9.2'

##########
# Devise already comes with oauth2 support,
# so we just need to put this gems in the Gemfile:
# gem 'devise', :git => "http://github.com/plataformatec/devise.git"
gem 'devise', '~> 1.4.9'

##########
# Databases
#
# Mongo
gem "mongoid", "2.3.3"
gem 'mongo', '= 1.3.1'
gem 'bson', '= 1.3.1'
gem 'bson_ext', '= 1.3.1'
gem 'mongoid_taggable'

# Redis
gem 'redis', '2.2.1'
gem 'ohm', :git => "https://github.com/Factlink/ohm.git" # we need the tribalvibes fork (0.1.4), for polymorphism
gem 'ohm-contrib', :git => 'http://github.com/Factlink/ohm-contrib.git'

##########
# Pagination & sorting
gem 'will_paginate', '~> 3.0'

#########
# Mustache
gem 'mustache'
gem 'mustache_rails3', :git => "https://github.com/Factlink/mustache_rails3.git"

##########
# Everyone loves JSON
gem 'json'

##########
# Email on errors
group :testserver, :staging, :production do
  gem 'exception_notification', :require => 'exception_notifier'
end

##########
# Whoo, full text search!
#
# Install SunSpot:
# https://github.com/sunspot/sunspot/wiki/adding-sunspot-search-to-rails-in-5-minutes-or-less
#
# Using SunSpot for Mongoid, Ruby wrapper for Solr
gem "sunspot_solr", "~> 1.3.0"
gem 'sunspot_rails', '~> 1.3.0'
gem 'sunspot_mongoid', :git => 'https://github.com/Factlink/sunspot_mongoid.git'

#needed for migrations to be compatible when no sql backend is available
gem "mongoid_rails_migrations", '0.0.13'


# Andand is a library to handle nil more easily
# http://andand.rubyforge.org/
# gem 'andand'
# newer version does not give creepy warning:
gem 'andand', :git => 'http://github.com/Factlink/andand.git'

# Deployment
gem 'capistrano', :require => false
gem 'capistrano-ext', :require => false

# imagemagick
gem 'rmagick', :require => 'RMagick'

# Avatars
gem "mongoid-paperclip", :require => "mongoid_paperclip"

# authorization
gem "cancan"

group :assets do
  # Temporary fix for @import bug, merge back to original Gem when it's in master
  gem 'less-rails', :git => "http://github.com/Factlink/less-rails.git"
  gem 'uglifier'

  ###########
  # jQuery
  gem 'jquery-rails', '>= 1.0.17'
  gem 'less-rails-bootstrap',  :git => 'http://github.com/Factlink/less-rails-bootstrap.git'
  gem "modernizr-rails", "~> 2.0.6"
end

group :development do
  gem "pry", :require => false

  #for static files serving
  gem 'rack'
  gem 'thin'
end

group :development, :test do
  gem 'metric_fu', :require => false
  # dependencies of metric_fu:
    gem "fattr", :require => false
    gem "arrayfields", :require => false
    gem "map", :require => false
    #use simplecov:
    gem 'simplecov', :require => false
    gem 'simplecov-rcov-text', :require => false

  gem 'webrat'

  # Profiling
  gem 'ruby-prof'

  gem 'rspec-rails'
  gem "factory_girl_rails" #factories for easy creation of a lot of objects
  gem "factory_girl"
  gem "database_cleaner"
  gem "mock_redis"

  gem 'jasmine'
  gem 'jasmine-headless-webkit'
end
