worker: bundle exec rake environment resque:work QUEUE=*
webserver: bundle exec thin start
recalculate: bundle exec rake fact_graph:recalculate
static: bundle exec script/static.rb
proxy: supervisor --quiet --watch ../web-proxy ../web-proxy/server.js
resqueweb: bundle exec resque-web -F -L config/initializers/resque.rb
