# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
require 'rake'
require 'metric_fu'
MetricFu::Configuration.run do |config|  
  config.metrics -= [:rcov]  
  #config.metrics -= [:reek]  
  #config.metrics -= [:flay]  
  config.metrics -= [:flog]
end
# Again deprecation warning
include Rake::DSL

FactlinkUI::Application.load_tasks



