# coding: utf-8

load_fact_data do

user "merijn", "merijn@gmail.com", "123hoi", "merijn481"
user "tom", "tom@codigy.nl", "123hoi", "tomdev"
user "jordin", "jordin@factlink.com", "123hoi", "vanzwoljj"
user "remon", "remon@factlink.com", "123hoi", "R51"
user "salvador", "salvador@factlink.com", "123hoi", "salvadorven"
user "mark", "mark@factlink.com", "123hoi", "markijbema"
user "joel", "joel@factlink.com", "123hoi", "joelkuiper"
user "luit", "luit@factlink.com", "123hoi", "LuitvD"


user "tom"
  fact "Oil is still detrimental to the environment,", "http://www.sciencedaily.com/releases/2011/08/110801111752.htm"
    believers "merijn","tom","joel"
    disbelievers "remon","mark","luit"
    doubters "salvador"
  fact "Molecules that are not accessible to microbes persist and could have toxic effects", "http://www.sciencedaily.com/releases/2011/08/110801111752.htm"
    believers "merijn","tom"
    disbelievers "remon","mark","joel"
  fact "Oil that is consumed by microbes \"is being converted to carbon dioxide that still gets into the atmosphere.\"", "http://www.sciencedaily.com/releases/2011/08/110801111752.htm"
    believers "merijn","joel"
    disbelievers "tom","mark"
    doubters "salvador","luit"
  fact "The dynamic microbial community of the Gulf of Mexico supported remarkable rates of oil respiration, despite a dearth of dissolved nutrients,", "http://www.sciencedaily.com/releases/2011/08/110801111752.htm"
    believers "tom","mark"
    disbelievers "merijn","joel"
    doubters "salvador","luit"
  fact "Microbes had the metabolic potential to break down a large portion of hydrocarbons and keep up with the flow rate from the wellhead", "http://www.sciencedaily.com/releases/2011/08/110801111752.htm"
    disbelievers "joel"
    doubters "tom"
  fact "the molecules that are not accessible to microbes persist and could have toxic effects", "http://example.org/"
    disbelievers "tom"
    doubters "joel"
  fact "Cook served as Apple CEO for two months in 2004, when Jobs was recovering from pancreatic cancer surgery. In 2009, Cook again served as Apple CEO for several months while Jobs took a leave of absence for a liver transplant.", "http://en.wikipedia.org/wiki/Tim_Cook"
    believers "tom","joel"
  fact "Most bacterial infections can be treated with antibiotics such as penicillin, discovered decades ago. However, such drugs are useless against viral infections", "http://www.sciencedaily.com/"
    believers "tom","joel"

user "tom"
  fact_relation "the molecules that are not accessible to microbes persist and could have toxic effects", :supporting, "Oil is still detrimental to the environment,"
    believers "merijn","tom","jordin","joel"
    disbelievers "remon","salvador"
  fact_relation "Oil that is consumed by microbes \"is being converted to carbon dioxide that still gets into the atmosphere.\"", :supporting, "Oil is still detrimental to the environment,"
    doubters "tom"
  fact_relation "Microbes had the metabolic potential to break down a large portion of hydrocarbons and keep up with the flow rate from the wellhead", :weakening, "Oil is still detrimental to the environment,"
    believers "tom"
  fact_relation "the molecules that are not accessible to microbes persist and could have toxic effects", :supporting, "Cook served as Apple CEO for two months in 2004, when Jobs was recovering from pancreatic cancer surgery. In 2009, Cook again served as Apple CEO for several months while Jobs took a leave of absence for a liver transplant."
    disbelievers "tom"
  fact_relation "Cook served as Apple CEO for two months in 2004, when Jobs was recovering from pancreatic cancer surgery. In 2009, Cook again served as Apple CEO for several months while Jobs took a leave of absence for a liver transplant.", :supporting, "Molecules that are not accessible to microbes persist and could have toxic effects"
    disbelievers "tom"
  fact_relation "Microbes had the metabolic potential to break down a large portion of hydrocarbons and keep up with the flow rate from the wellhead", :supporting, "Molecules that are not accessible to microbes persist and could have toxic effects"
    believers "tom"
  fact_relation "Cook served as Apple CEO for two months in 2004, when Jobs was recovering from pancreatic cancer surgery. In 2009, Cook again served as Apple CEO for several months while Jobs took a leave of absence for a liver transplant.", :supporting, "the molecules that are not accessible to microbes persist and could have toxic effects"
    disbelievers "tom"
  fact_relation "Cook served as Apple CEO for two months in 2004, when Jobs was recovering from pancreatic cancer surgery. In 2009, Cook again served as Apple CEO for several months while Jobs took a leave of absence for a liver transplant.", :supporting, "Most bacterial infections can be treated with antibiotics such as penicillin, discovered decades ago. However, such drugs are useless against viral infections"
    disbelievers "tom"

user "tom"
  channel "War & Peace"
    add_fact "Oil is still detrimental to the environment,"
    add_fact "Molecules that are not accessible to microbes persist and could have toxic effects"
    add_fact "Oil that is consumed by microbes \"is being converted to carbon dioxide that still gets into the atmosphere.\""
    add_fact "The dynamic microbial community of the Gulf of Mexico supported remarkable rates of oil respiration, despite a dearth of dissolved nutrients,"
    add_fact "Microbes had the metabolic potential to break down a large portion of hydrocarbons and keep up with the flow rate from the wellhead"
    add_fact "the molecules that are not accessible to microbes persist and could have toxic effects"
    add_fact "Cook served as Apple CEO for two months in 2004, when Jobs was recovering from pancreatic cancer surgery. In 2009, Cook again served as Apple CEO for several months while Jobs took a leave of absence for a liver transplant."
    del_fact "Cook served as Apple CEO for two months in 2004, when Jobs was recovering from pancreatic cancer surgery. In 2009, Cook again served as Apple CEO for several months while Jobs took a leave of absence for a liver transplant."
    sub_channel "joel", "War & Peace"
  channel "Oil"
    add_fact "Oil is still detrimental to the environment,"
    add_fact "Molecules that are not accessible to microbes persist and could have toxic effects"
    add_fact "Oil that is consumed by microbes \"is being converted to carbon dioxide that still gets into the atmosphere.\""
    add_fact "The dynamic microbial community of the Gulf of Mexico supported remarkable rates of oil respiration, despite a dearth of dissolved nutrients,"
    add_fact "Microbes had the metabolic potential to break down a large portion of hydrocarbons and keep up with the flow rate from the wellhead"
    add_fact "Cook served as Apple CEO for two months in 2004, when Jobs was recovering from pancreatic cancer surgery. In 2009, Cook again served as Apple CEO for several months while Jobs took a leave of absence for a liver transplant."
    add_fact "Most bacterial infections can be treated with antibiotics such as penicillin, discovered decades ago. However, such drugs are useless against viral infections"
    del_fact "Cook served as Apple CEO for two months in 2004, when Jobs was recovering from pancreatic cancer surgery. In 2009, Cook again served as Apple CEO for several months while Jobs took a leave of absence for a liver transplant."

user "joel"
  channel "War & Peace"
    add_fact "Molecules that are not accessible to microbes persist and could have toxic effects"
    add_fact "Most bacterial infections can be treated with antibiotics such as penicillin, discovered decades ago. However, such drugs are useless against viral infections"
  channel "Climate Change"
    add_fact "Molecules that are not accessible to microbes persist and could have toxic effects"
    add_fact "Most bacterial infections can be treated with antibiotics such as penicillin, discovered decades ago. However, such drugs are useless against viral infections"
  channel "The new web"
    add_fact "Cook served as Apple CEO for two months in 2004, when Jobs was recovering from pancreatic cancer surgery. In 2009, Cook again served as Apple CEO for several months while Jobs took a leave of absence for a liver transplant."
end