user "merijn", "merijn@gmail.com"
user "tomdev", "tom@codigy.nl"
user "jordin", "jordin@factlink.com"
user "remon", "remon@factlink.com"
user "salvador", "salvador@factlink.com"
user "mark", "mark@factlink.com"
user "joel", "joel@factlink.com"


user "joel"
  fact "Batman is a fictional character created by the artist Bob Kane and writer Bill Finger", "http://en.wikipedia.org/wiki/Batman"
  fact "Batman's secret identity is Bruce Wayne", "http://en.wikipedia.org/wiki/Batman"
  fact "Batman operates in the fictional American Gotham City", "http://en.wikipedia.org/wiki/Batman"
  fact "He fights an assortment of villains such as the Joker, the Penguin, Two-Face, Poison Ivy and Catwoman", "http://en.wikipedia.org/wiki/Batman"
    believers "salvador"
  fact "The late 1960s Batman television series used a camp aesthetic which continued to be associated with the character for years after the show ended", "http://en.wikipedia.org/wiki/Batman"
  fact "example is example", "http://example.org/"
  fact "ex", "http://example.org/"
    believers "salvador"
  fact "je moeder", "http://example.org/"
    doubters "salvador"
  fact "example is examples", "http://example.org/"

user "salvador"
  fact_relation "je moeder", :supporting, "Batman is a fictional character created by the artist Bob Kane and writer Bill Finger"
    believers "salvador"
  fact_relation "ex", :weakening, "Batman is a fictional character created by the artist Bob Kane and writer Bill Finger"
    believers "salvador"

user "joel"
  fact_relation "je moeder", :supporting, "example is examples"
  fact_relation "He fights an assortment of villains such as the Joker, the Penguin, Two-Face, Poison Ivy and Catwoman", :supporting, "Batman is a fictional character created by the artist Bob Kane and writer Bill Finger"
    believers "salvador"
