user "johndoe1", "johndoe1@example.com"
user "johndoe2", "johndoe2@example.com"
user "johndoe3", "johndoe3@example.com"
user "johndoe4", "johndoe4@example.com"
user "johndoe5", "johndoe5@example.com"
user "merijn", "merijn@gmail.com"
user "tomdev", "tom@codigy.nl"
user "jordin", "jordin@factlink.com"
user "remon", "remon@factlink.com"
user "salvador", "salvador@factlink.com"
user "mark", "mark@factlink.com"
user "joel", "joel@factlink.com"
user "john_doe_x", "jd@jd.com"


user "johndoe1"
  fact "Batman is a fictional character created by the artist Bob Kane and writer Bill Finger", "http://en.wikipedia.org/wiki/Batman"
    believers "merijn"

user "johndoe2"
  fact "Batman's secret identity is Bruce Wayne", "http://en.wikipedia.org/wiki/Batman"
    believers "merijn","tomdev"

user "johndoe3"
  fact "Batman operates in the fictional American Gotham City", "http://en.wikipedia.org/wiki/Batman"

user "johndoe4"
  fact "He fights an assortment of villains such as the Joker, the Penguin, Two-Face, Poison Ivy and Catwoman", "http://en.wikipedia.org/wiki/Batman"

user "johndoe5"
  fact "The late 1960s Batman television series used a camp aesthetic which continued to be associated with the character for years after the show ended", "http://en.wikipedia.org/wiki/Batman"

user "merijn"
  fact "example is example", "http://example.org/"
  fact "", "http://en.wikipedia.org/wiki/Batman"
  fact "", "http://en.wikipedia.org/wiki/Batman"
  fact "The spill caused extensive damage to marine and wildlife habitats and to the Gulf's fishing and tourism industries", "http://en.wikipedia.org/wiki/Deepwater_Horizon_oil_spill"
  fact "Charles Miller is a computer security researcher with the consulting firm Accuvant LABS", "http://en.wikipedia.org/wiki/Charlie_Miller_(security_researcher)"
  fact "", "http://en.wikipedia.org/wiki/Batman"
  fact "", "http://en.wikipedia.org/wiki/Batman"
  fact "AngelList may be a game-changer, but most of the same rules are still in place.", "http://onstartups.com/tabid/3339/bid/63010/Raising-Money-On-AngelList-21-Tips-From-Two-Active-Angels.aspx"
  fact "", "http://onstartups.com/tabid/3339/bid/63010/Raising-Money-On-AngelList-21-Tips-From-Two-Active-Angels.aspx"
  fact "400 investments. A startup has been introduced to an investor and subsequently closed that investor over 400 times.", "venturehacks.com"
    believers "merijn"
  fact "Court strikes down Obama health insurance mandate", "http://www.usatoday.com/news/washington/2011-08-12-health-care-ruling_n.htm"
  fact "In decision, divided three-judge panel sides with 26 states that had sued to block the law.", "http://washingtonpost.com"
    believers "merijn"
  fact "Through this machine, Bush hoped to transform an information explosion into a knowledge explosion.", "http://en.wikipedia.org/wiki/As_We_May_Think"
  fact " this is why love is such an existential threat to the techno-consumerist order: it exposes the lie.", "http://www.kk.org/thetechnium/archives/2011/07/found_quotes_8.php?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+thetechnium+%28The+Technium%29"
  fact "this is why love is such an existential threat to the techno-consumerist order: it exposes the lie", "http://www.kk.org/thetechnium/archives/2011/07/found_quotes_8.php?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+thetechnium+%28The+Technium%29"
  fact "There is no such thing as a person whose real self you like every particle of. This is why a world of liking is ultimately a lie. But there is such a thing as a person whose real self you love every particle of", "http://www.nytimes.com/2011/05/29/opinion/29franzen.html?pagewanted=2&_r=1"
  fact "Despite appearances for either Bert or Ernie being gay or heterosexual, Sesame Workshop states that the two \"do not have a sexual orientation", "http://en.wikipedia.org/wiki/Bert_and_Ernie"
  fact "Bert and Ernie will not be getting married. To each other, or anyone else.", "http://www.huffingtonpost.com/2011/08/11/bert-and-ernie-gay-marriage-no_n_924808.html"
    believers "merijn"
  fact " people find credibility in the world's information.            The service is built on the belief that inf", "http://factlink.org"
    believers "merijn"
  fact "Because the syndicate has done deals with the regimes in strife-torn places, such as Zimbabwe and Guinea, it may also have indirectly helped sustain violent conflicts.", "http://www.economist.com/node/21525847"
  fact "Société Générale, the country’s third-biggest bank, fell by almost a fifth before recovering some ground and closing down 15%", "http://www.economist.com/blogs/freeexchange/2011/08/french-fears"
  fact "France will keep its triple-A rating after Standard & Poor’s cut America’s on August 5th", "http://www.economist.com/blogs/freeexchange/2011/08/french-fears"
  fact "German Bunds jumped to almost triple the average level of 2010 while the cost of insuring against a default by France reached new highs during the week", "http://www.economist.com/blogs/freeexchange/2011/08/french-fears"
  fact "best known as the home of Batman", "http://en.wikipedia.org/wiki/Gotham_City"
  fact "Credibility you can see", "http://factlink.org"
    believers "merijn"
  fact "Google to Buy Motorola Mobility for $12.5 Billion", "http://www.nytimes.com/pages/technology/index.html"
  fact "Google to Acquire Motorola Mobility", "http://mediacenter.motorola.com/Press-Releases/Google-to-Acquire-Motorola-Mobility-3797.aspx"
    believers "merijn"
  fact "Google to Buy Motorola Mobility for $12.5 Billion", "http://dealbook.nytimes.com/2011/08/15/google-to-buy-motorola-mobility/?ref=technology"
  fact "Google to Acquire Motorola Mobility", "http://investor.google.com/releases/2011/0815.html"
    believers "merijn"
  fact "Google to Buy Motorola Mobility for $12.5 Billion", "http://dealbook.nytimes.com/2011/08/15/google-to-buy-motorola-mobility/"
  fact "He bought the other owners out in March 1987 and ", "http://en.wikipedia.org/wiki/Coffee"
  fact "Coffee is a brewed beverage with a dark, slightly acidic flavor prepared from the roasted seeds of the coffee plant, colloquially called coffee beans.", "http://en.wikipedia.org/wiki/Coffee"
  fact " a beverage made by percolation, infusion, or decoction from the roasted and ground seeds of a coffee plant", "http://www.merriam-webster.com/dictionary/coffee"
    believers "merijn"
  fact "Macs are just PCs manufactured by Apple.", "http://www.hiprank.com/mac-vs-pc.html"

user "tomdev"
  fact "ex", "http://example.org/"
  fact "offee was initially used for spiritual reasons. At least 1,100 years ago", "http://en.wikipedia.org/wiki/Coffee"

user "jordin"
  fact "je moeder", "http://example.org/"

user "remon"
  fact "example is examples", "http://example.org/"

user "john_doe_x"
  fact "Since Blackberry’s (Research In Motion) market share has dropped precipitously, the Android and the iPhone have been left standing alone at the top of the smartphone heap", "http://www.decodedscience.com/google-buys-motorolas-mobile-division-leg-up-in-cell-wars/2481"
  fact "RIM Loses More U.S. Market Share To Apple, Google", "http://www.huffingtonpost.com/2011/06/03/rim-market-share_n_871129.html"
    believers "john_doe_x"
  fact "RIM's share has plummeted to 29%", "http://www.businessinsider.com/android-iphone-market-share-2011-4"
    believers "john_doe_x"
  fact "Android's growth of 7.7 percent over the previous quarter pushed the Google mobile operating system to 31.2 percent share, past RIM's 30.4 percent share.", "http://www.appleinsider.com/articles/11/03/07/android_tops_rim_in_us_smartphone_market_share_apples_iphone_third.html"
    believers "john_doe_x"
  fact "RIM's BlackBerry 7 Models Could Prove Good Enough to Win Back Buyers", "http://www.eweek.com/c/a/Mobile-and-Wireless/RIMs-BlackBerry-7-Models-Could-Prove-Good-Enough-to-Win-Back-Buyers-643692/"
    believers "john_doe_x"
  fact "Sun CEO explicitly endorsed Java's use in Android", "http://www.zdnet.com/blog/open-source/sun-ceo-explicitly-endorsed-javas-use-in-android-what-do-you-say-now-oracle/9285"
  fact "Groklaw has dug up proof that when Google first introduced Android, Sun, Java’s creator, was all in favor of its use of Java.", "http://www.zdnet.com/blog/open-source/sun-ceo-explicitly-endorsed-javas-use-in-android-what-do-you-say-now-oracle/9285"
    believers "john_doe_x"
  fact "Oracle scrubs site of embarrassing Java blog", "http://news.cnet.com/8301-1023_3-20082151-93/scoop-oracle-scrubs-site-of-embarrassing-java-blog/?part=rss&subj=news&tag=2547-1_3-0-20"
    believers "merijn","john_doe_x"

user "merijn"
  fact_relation "The spill caused extensive damage to marine and wildlife habitats and to the Gulf's fishing and tourism industries", :supporting, "Batman is a fictional character created by the artist Bob Kane and writer Bill Finger"
  fact_relation "Charles Miller is a computer security researcher with the consulting firm Accuvant LABS", :weakening, "Batman is a fictional character created by the artist Bob Kane and writer Bill Finger"
  fact_relation "400 investments. A startup has been introduced to an investor and subsequently closed that investor over 400 times.", :supporting, ""
  fact_relation "400 investments. A startup has been introduced to an investor and subsequently closed that investor over 400 times.", :supporting, "AngelList may be a game-changer, but most of the same rules are still in place."
    doubters "merijn"
  fact_relation "In decision, divided three-judge panel sides with 26 states that had sued to block the law.", :supporting, "Court strikes down Obama health insurance mandate"
    believers "merijn"
  fact_relation "Bert and Ernie will not be getting married. To each other, or anyone else.", :supporting, "Despite appearances for either Bert or Ernie being gay or heterosexual, Sesame Workshop states that the two \"do not have a sexual orientation"
    believers "merijn"
  fact_relation " people find credibility in the world's information.            The service is built on the belief that inf", :weakening, "Despite appearances for either Bert or Ernie being gay or heterosexual, Sesame Workshop states that the two \"do not have a sexual orientation"
    disbelievers "merijn"
  fact_relation "Bert and Ernie will not be getting married. To each other, or anyone else.", :supporting, "Société Générale, the country’s third-biggest bank, fell by almost a fifth before recovering some ground and closing down 15%"
    believers "merijn"
  fact_relation "Batman's secret identity is Bruce Wayne", :supporting, "Société Générale, the country’s third-biggest bank, fell by almost a fifth before recovering some ground and closing down 15%"
    believers "merijn"
  fact_relation "Batman is a fictional character created by the artist Bob Kane and writer Bill Finger", :supporting, "Bert and Ernie will not be getting married. To each other, or anyone else."
  fact_relation "best known as the home of Batman", :supporting, "Batman is a fictional character created by the artist Bob Kane and writer Bill Finger"
  fact_relation "Credibility you can see", :supporting, "Batman is a fictional character created by the artist Bob Kane and writer Bill Finger"
    believers "merijn"
  fact_relation "Google to Acquire Motorola Mobility", :supporting, "Google to Buy Motorola Mobility for $12.5 Billion"
    believers "merijn"
  fact_relation "Google to Acquire Motorola Mobility", :supporting, "Google to Buy Motorola Mobility for $12.5 Billion"
    believers "merijn"
  fact_relation "Google to Acquire Motorola Mobility", :supporting, "Google to Buy Motorola Mobility for $12.5 Billion"
    believers "merijn"
  fact_relation "Google to Acquire Motorola Mobility", :supporting, "Google to Buy Motorola Mobility for $12.5 Billion"
    believers "merijn"
  fact_relation " a beverage made by percolation, infusion, or decoction from the roasted and ground seeds of a coffee plant", :supporting, "Coffee is a brewed beverage with a dark, slightly acidic flavor prepared from the roasted seeds of the coffee plant, colloquially called coffee beans."
    believers "merijn"
  fact_relation "Oracle scrubs site of embarrassing Java blog", :supporting, "RIM's BlackBerry 7 Models Could Prove Good Enough to Win Back Buyers"
    doubters "merijn"

user "tomdev"
  fact_relation "Batman's secret identity is Bruce Wayne", :supporting, "offee was initially used for spiritual reasons. At least 1,100 years ago"
    believers "tomdev"

user "salvador"
  fact_relation "je moeder", :supporting, "example is examples"

user "mark"
  fact_relation "He fights an assortment of villains such as the Joker, the Penguin, Two-Face, Poison Ivy and Catwoman", :supporting, "Batman is a fictional character created by the artist Bob Kane and writer Bill Finger"

user "john_doe_x"
  fact_relation "RIM's share has plummeted to 29%", :supporting, "Since Blackberry’s (Research In Motion) market share has dropped precipitously, the Android and the iPhone have been left standing alone at the top of the smartphone heap"
    believers "john_doe_x"
  fact_relation "Android's growth of 7.7 percent over the previous quarter pushed the Google mobile operating system to 31.2 percent share, past RIM's 30.4 percent share.", :supporting, "Since Blackberry’s (Research In Motion) market share has dropped precipitously, the Android and the iPhone have been left standing alone at the top of the smartphone heap"
    doubters "john_doe_x"
  fact_relation "RIM Loses More U.S. Market Share To Apple, Google", :supporting, "Since Blackberry’s (Research In Motion) market share has dropped precipitously, the Android and the iPhone have been left standing alone at the top of the smartphone heap"
    believers "john_doe_x"
  fact_relation "RIM's BlackBerry 7 Models Could Prove Good Enough to Win Back Buyers", :weakening, "Since Blackberry’s (Research In Motion) market share has dropped precipitously, the Android and the iPhone have been left standing alone at the top of the smartphone heap"
    believers "john_doe_x"
  fact_relation "Groklaw has dug up proof that when Google first introduced Android, Sun, Java’s creator, was all in favor of its use of Java.", :supporting, "Sun CEO explicitly endorsed Java's use in Android"
    believers "john_doe_x"
  fact_relation "Oracle scrubs site of embarrassing Java blog", :supporting, "Sun CEO explicitly endorsed Java's use in Android"
    believers "john_doe_x"

user "merijn"
  channel "Mobile wars"
    add_fact "RIM's BlackBerry 7 Models Could Prove Good Enough to Win Back Buyers"
    sub_channel "john_doe_x", "Mobile wars"
  channel "Coffee"
    add_fact "Coffee is a brewed beverage with a dark, slightly acidic flavor prepared from the roasted seeds of the coffee plant, colloquially called coffee beans."
  channel "Mac vs PC"
    add_fact "Macs are just PCs manufactured by Apple."

user "tomdev"
  channel "Mobile wars"
    sub_channel "merijn", "Mobile wars"

user "john_doe_x"
  channel "Mobile wars"
    add_fact "Google to Buy Motorola Mobility for $12.5 Billion"
    add_fact "Since Blackberry’s (Research In Motion) market share has dropped precipitously, the Android and the iPhone have been left standing alone at the top of the smartphone heap"
    add_fact "Sun CEO explicitly endorsed Java's use in Android"
  channel "Climate change"
    del_fact "Google to Buy Motorola Mobility for $12.5 Billion"
    sub_channel "john_doe_x", "Mobile wars"
