default: &defaults
  # Your push api key, it is possible to set this dynamically using ERB:
  push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"

  # Your app's name
  name: "<%= ENV['APPSIGNAL_PUSH_API_NAME'] %>"

  # The cuttoff point in ms above which a request is considered slow, default is 200
  slow_request_threshold: 240

# Configuration per environment, leave out an environment or set active
# to false to not push metrics for that environment.
development:
  active: false

production:
  <<: *defaults
  active: true

staging:
  <<: *defaults
  active: true
