development:
  static:
    hostname: localhost
    port: 8000
    protocol: http://

test:
  static:
    hostname: localhost
    port: 8000
    protocol: http://

staging:
  static:
    hostname: factlink-static-staging.inverselink.com
    port: 443
    protocol: https://

production:
  static:
    hostname: static.factlink.com
    port: 443
    protocol: https://
