#!/bin/bash
eval "$(rbenv init -)"

#abort this script on any error:
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BASE_DIR="$( cd "${DIR}"&& cd ../.. && pwd )"

if [ ! -d "$BASE_DIR/core/.git" ]; then
  echo "No core repo detected, installing all repo's in $BASE_DIR."
  read -p "Proceed? (y/N)" resp && echo $resp | egrep "^[yY]"
fi

#below are a few idempotent installer helper functions for git, brew and gem.
#npm install is already idempotent, it needs no helper function.
function cloneRepo {
  if [ ! -d "$1/.git" ]; then
    echo "cloning factlink $1 repo"
    git clone "git@github.com:Factlink/$1.git"
  else
    echo "$1 repo already present; only fetching"
  fi
  pushd $1
    git feetch
  popd
}

cd "$BASE_DIR"

cloneRepo server-management
cloneRepo core
cloneRepo chrome-extension
cloneRepo firefox-extension
cloneRepo js-library
cloneRepo web-proxy
cloneRepo chef-repo

RUBY_VERSION=`cat core/.ruby-version`

echo "Checking for ruby ${RUBY_VERSION}"

rbenv rehash || :
if bash -c "rbenv global ${RUBY_VERSION}" ; then
  #NOTE: we need to run the rbenv global TEST in a separate bash instance
  #because rbenv installs a bash function and due to set -e interaction in can fail.
  echo "Ruby ${RUBY_VERSION} already installed."
else
    echo "Installing ruby ${RUBY_VERSION}..."
    rbenv install ${RUBY_VERSION}
    rbenv rehash || :
fi

if ! type grunt 2>&1 >/dev/null; then
  #/usr/local/share/npm/bin isn't yet in path
  export PATH=$PATH:/usr/local/share/npm/bin
  if ! type grunt 2>&1 >/dev/null; then
    echo "ERROR: Cannot find grunt in path nor in /usr/local/share/npm/bin; exiting."
    exit 1
  fi
  echo 'export PATH=$PATH:/usr/local/share/npm/bin' >> ~/.bash_profile
fi

rbenv shell "${RUBY_VERSION}"

gem install bundler foreman git-up
rbenv rehash || :
rbenv shell --unset

pushd web-proxy
  bin/bootstrap
popd

pushd chrome-extension
  bin/bootstrap
popd

pushd firefox-extension
  bin/bootstrap
popd

pushd js-library
  bin/bootstrap
popd

# pushd chef-repo
# RSO broke the chef-repo bootstrap script, so this is currently disabled.
#  ./script/bootstrap
# popd

pushd core
  bin/bootstrap
popd

echo "Your factlink development environment is done.  Happy hacking!"
