source "http://rubygems.org/"

gem "goliath"
gem "eventmachine"
gem 'em-synchrony'
gem 'em-http-request'
gem 'addressable'
gem 'sentry-raven'
gem 'approvals', github: 'kytrinyx/approvals'
gem 'rspec', '~> 3.0.0.beta2'
