development:
    core:
        hostname: localhost
        port: 3000
        protocol: http://

test:
    core:
        hostname: localhost
        port: 3000
        protocol: http://

staging:
    core:
        hostname: factlink-staging.inverselink.com
        port: 443
        protocol: https://

production:
    core:
        hostname: factlink.com
        port: 443
        protocol: https://
