development:
  static:
    hostname: localhost
    port: 8000
    protocol: http://
    salt: 'tJx,RiGj:\(HPunB0.FX'

test:
  static:
    hostname: localhost
    port: 8000
    protocol: http://
    salt: 'tJx,RiGj:\(HPunB0.FX'

testserver:
  static:
    hostname: factlink-static-testserver.inverselink.com
    port: 443
    protocol: https://
    salt: 'tJx,RiGj:\(HPunB0.FX'

staging:
  static:
    hostname: factlink-static-staging.inverselink.com
    port: 443
    protocol: https://
    salt: 'tJx,RiGj:\(HPunB0.FX'

production:
  static:
    hostname: static.factlink.com
    port: 443
    protocol: https://
    salt: 'tJx,RiGj:\(HPunB0.FX'
